version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  spring_grpc: 
    build: ./grpcexample # specify the directory of the Dockerfile
    container_name: spring_grpc
    ports:
      - "1020:1020" #specify ports forwarding
    links:
      - mongodb
  spring-reactive-mondo-db: 
    build: ./spring-reactive-mongo-db # specify the directory of the Dockerfile
    container_name: spring-reactive-mongo-db
    ports:
      - "8090:8090" #specify ports forwarding
    links:
      - mongodb

  mongodb: # name of the third service
    image: mongo # specify image to build container from
    command: mongod --port 27019
    ports:
      - "27019:27019" # specify port forewarding
