// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.om.example.grpc.struct.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addressLine1 = 1;</code>
   */
  String getAddressLine1();
  /**
   * <code>string addressLine1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressLine1Bytes();

  /**
   * <code>string addressLine2 = 2;</code>
   */
  String getAddressLine2();
  /**
   * <code>string addressLine2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressLine2Bytes();

  /**
   * <code>string city = 3;</code>
   */
  String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string province = 4;</code>
   */
  String getProvince();
  /**
   * <code>string province = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string postalCode = 5;</code>
   */
  String getPostalCode();
  /**
   * <code>string postalCode = 5;</code>
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();
}
