// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public interface AllEmployeesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.om.example.grpc.struct.AllEmployees)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.om.example.grpc.struct.Employee items = 1;</code>
   */
  java.util.List<Employee>
      getItemsList();
  /**
   * <code>repeated .com.om.example.grpc.struct.Employee items = 1;</code>
   */
  Employee getItems(int index);
  /**
   * <code>repeated .com.om.example.grpc.struct.Employee items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.om.example.grpc.struct.Employee items = 1;</code>
   */
  java.util.List<? extends EmployeeOrBuilder>
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.om.example.grpc.struct.Employee items = 1;</code>
   */
  EmployeeOrBuilder getItemsOrBuilder(
          int index);
}
