// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_om_example_grpc_struct_EmployeeRequestByPhone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_om_example_grpc_struct_EmployeeRequestByPhone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_om_example_grpc_struct_EmployeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_om_example_grpc_struct_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_om_example_grpc_struct_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_om_example_grpc_struct_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_om_example_grpc_struct_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_om_example_grpc_struct_AllEmployees_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_om_example_grpc_struct_AllEmployees_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016employee.proto\022\032com.om.example.grpc.st" +
      "ruct\"\'\n\026EmployeeRequestByPhone\022\r\n\005phone\030" +
      "\001 \001(\t\"J\n\020EmployeeResponse\0226\n\010employee\030\001 " +
      "\001(\0132$.com.om.example.grpc.struct.Employe" +
      "e\"\201\001\n\010Employee\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010las" +
      "tName\030\002 \001(\t\022\r\n\005phone\030\003 \001(\t\022\013\n\003age\030\004 \001(\005\022" +
      "4\n\007address\030\005 \001(\0132#.com.om.example.grpc.s" +
      "truct.Address\"i\n\007Address\022\024\n\014addressLine1" +
      "\030\001 \001(\t\022\024\n\014addressLine2\030\002 \001(\t\022\014\n\004city\030\003 \001" +
      "(\t\022\020\n\010province\030\004 \001(\t\022\022\n\npostalCode\030\005 \001(\t" +
      "\"C\n\014AllEmployees\0223\n\005items\030\001 \003(\0132$.com.om" +
      ".example.grpc.struct.Employee2\350\001\n\017Employ" +
      "eeService\022u\n\031getEmployeeDetailsByPhone\0222" +
      ".com.om.example.grpc.struct.EmployeeRequ" +
      "estByPhone\032$.com.om.example.grpc.struct." +
      "Employee\022^\n\014getEmployees\022$.com.om.exampl" +
      "e.grpc.struct.Employee\032(.com.om.example." +
      "grpc.struct.AllEmployeesB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_om_example_grpc_struct_EmployeeRequestByPhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_om_example_grpc_struct_EmployeeRequestByPhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_om_example_grpc_struct_EmployeeRequestByPhone_descriptor,
        new String[] { "Phone", });
    internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_om_example_grpc_struct_EmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor,
        new String[] { "Employee", });
    internal_static_com_om_example_grpc_struct_Employee_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_om_example_grpc_struct_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_om_example_grpc_struct_Employee_descriptor,
        new String[] { "FirstName", "LastName", "Phone", "Age", "Address", });
    internal_static_com_om_example_grpc_struct_Address_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_om_example_grpc_struct_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_om_example_grpc_struct_Address_descriptor,
        new String[] { "AddressLine1", "AddressLine2", "City", "Province", "PostalCode", });
    internal_static_com_om_example_grpc_struct_AllEmployees_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_om_example_grpc_struct_AllEmployees_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_om_example_grpc_struct_AllEmployees_descriptor,
        new String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
