// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.om.example.grpc.struct.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string phone = 3;</code>
   */
  String getPhone();
  /**
   * <code>string phone = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>int32 age = 4;</code>
   */
  int getAge();

  /**
   * <code>.com.om.example.grpc.struct.Address address = 5;</code>
   */
  boolean hasAddress();
  /**
   * <code>.com.om.example.grpc.struct.Address address = 5;</code>
   */
  Address getAddress();
  /**
   * <code>.com.om.example.grpc.struct.Address address = 5;</code>
   */
  AddressOrBuilder getAddressOrBuilder();
}
