// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public interface EmployeeRequestByPhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.om.example.grpc.struct.EmployeeRequestByPhone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone = 1;</code>
   */
  String getPhone();
  /**
   * <code>string phone = 1;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
