// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

public interface EmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.om.example.grpc.struct.EmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  boolean hasEmployee();
  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  Employee getEmployee();
  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  EmployeeOrBuilder getEmployeeOrBuilder();
}
