// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.om.example.grpc.struct;

/**
 * Protobuf type {@code com.om.example.grpc.struct.EmployeeResponse}
 */
public  final class EmployeeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.om.example.grpc.struct.EmployeeResponse)
    EmployeeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeResponse.newBuilder() to construct.
  private EmployeeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeResponse() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Employee.Builder subBuilder = null;
            if (employee_ != null) {
              subBuilder = employee_.toBuilder();
            }
            employee_ = input.readMessage(Employee.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(employee_);
              employee_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EmployeeOuterClass.internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EmployeeOuterClass.internal_static_com_om_example_grpc_struct_EmployeeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EmployeeResponse.class, EmployeeResponse.Builder.class);
  }

  public static final int EMPLOYEE_FIELD_NUMBER = 1;
  private Employee employee_;
  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  public boolean hasEmployee() {
    return employee_ != null;
  }
  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  public Employee getEmployee() {
    return employee_ == null ? Employee.getDefaultInstance() : employee_;
  }
  /**
   * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
   */
  public EmployeeOrBuilder getEmployeeOrBuilder() {
    return getEmployee();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (employee_ != null) {
      output.writeMessage(1, getEmployee());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (employee_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmployee());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EmployeeResponse)) {
      return super.equals(obj);
    }
    EmployeeResponse other = (EmployeeResponse) obj;

    boolean result = true;
    result = result && (hasEmployee() == other.hasEmployee());
    if (hasEmployee()) {
      result = result && getEmployee()
          .equals(other.getEmployee());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmployee()) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployee().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EmployeeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EmployeeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EmployeeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EmployeeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EmployeeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EmployeeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EmployeeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EmployeeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EmployeeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.om.example.grpc.struct.EmployeeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.om.example.grpc.struct.EmployeeResponse)
      EmployeeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeOuterClass.internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeOuterClass.internal_static_com_om_example_grpc_struct_EmployeeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeResponse.class, EmployeeResponse.Builder.class);
    }

    // Construct using com.om.example.grpc.struct.EmployeeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (employeeBuilder_ == null) {
        employee_ = null;
      } else {
        employee_ = null;
        employeeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EmployeeOuterClass.internal_static_com_om_example_grpc_struct_EmployeeResponse_descriptor;
    }

    public EmployeeResponse getDefaultInstanceForType() {
      return EmployeeResponse.getDefaultInstance();
    }

    public EmployeeResponse build() {
      EmployeeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public EmployeeResponse buildPartial() {
      EmployeeResponse result = new EmployeeResponse(this);
      if (employeeBuilder_ == null) {
        result.employee_ = employee_;
      } else {
        result.employee_ = employeeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EmployeeResponse) {
        return mergeFrom((EmployeeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EmployeeResponse other) {
      if (other == EmployeeResponse.getDefaultInstance()) return this;
      if (other.hasEmployee()) {
        mergeEmployee(other.getEmployee());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EmployeeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EmployeeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Employee employee_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Employee, Employee.Builder, EmployeeOrBuilder> employeeBuilder_;
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public boolean hasEmployee() {
      return employeeBuilder_ != null || employee_ != null;
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Employee getEmployee() {
      if (employeeBuilder_ == null) {
        return employee_ == null ? Employee.getDefaultInstance() : employee_;
      } else {
        return employeeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Builder setEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employee_ = value;
        onChanged();
      } else {
        employeeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Builder setEmployee(
        Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        employee_ = builderForValue.build();
        onChanged();
      } else {
        employeeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Builder mergeEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (employee_ != null) {
          employee_ =
            Employee.newBuilder(employee_).mergeFrom(value).buildPartial();
        } else {
          employee_ = value;
        }
        onChanged();
      } else {
        employeeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Builder clearEmployee() {
      if (employeeBuilder_ == null) {
        employee_ = null;
        onChanged();
      } else {
        employee_ = null;
        employeeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public Employee.Builder getEmployeeBuilder() {

      onChanged();
      return getEmployeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    public EmployeeOrBuilder getEmployeeOrBuilder() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilder();
      } else {
        return employee_ == null ?
            Employee.getDefaultInstance() : employee_;
      }
    }
    /**
     * <code>.com.om.example.grpc.struct.Employee employee = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Employee, Employee.Builder, EmployeeOrBuilder>
        getEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Employee, Employee.Builder, EmployeeOrBuilder>(
                getEmployee(),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.om.example.grpc.struct.EmployeeResponse)
  }

  // @@protoc_insertion_point(class_scope:com.om.example.grpc.struct.EmployeeResponse)
  private static final EmployeeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EmployeeResponse();
  }

  public static EmployeeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeResponse>() {
    public EmployeeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EmployeeResponse> getParserForType() {
    return PARSER;
  }

  public EmployeeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

